-- Query 5: total revenue generated by each hospital and pharmacy in a given month, along with their location
-- uses a union of two queries to combine the revenue generated by hospitals and pharmacies in a given month
-- uses left joins to include all hospitals and pharmacies in the result, even if they have no patients
-- uses the GROUP BY clause to aggregate the billing amounts for each facility, and selects the facility name, location, and revenue

SELECT h.hospital_name AS facility_name, h.hospital_location AS facility_location, SUM(b.billing_amount) AS revenue
FROM Hospital h
LEFT JOIN Patient p ON h.hospital_ID = p.hospital_ID
LEFT JOIN Billing b ON p.patient_ID = b.patient_ID
WHERE b.billing_date BETWEEN '2023-01-01' AND '2023-01-31'
GROUP BY h.hospital_ID
UNION ALL
SELECT ph.pharmacy_name AS facility_name, ph.pharmacy_location AS facility_location, SUM(b.billing_amount) AS revenue
FROM Pharmacy ph
LEFT JOIN Patient p ON ph.pharmacy_ID = p.patient_ID
LEFT JOIN Billing b ON p.patient_ID = b.patient_ID
WHERE b.billing_date BETWEEN '2023-01-01' AND '2023-01-31'
GROUP BY ph.pharmacy_ID;